name: Cov & Docs

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Coverage and Doxygen
      run: |
        sudo add-apt-repository ppa:wsnipex/mold-linker
        sudo apt-get update
        sudo apt-get install -y lcov doxygen libsdl2-dev mold
        sudo mkdir -p /usr/share/libexec/mold
        sudo ln -s `which mold` /usr/share/libexec/mold/ld
        make coverage
        grep -qF `printf "\e[1;32mtest.py suite passed all tests!\e[0m"` build/debug/log/test*.log
        make docs
        mv build/debug/cov website/
        mv build/debug/coverage.svg website/
        mv docs website/
        export CODACY_ORGANIZATION_PROVIDER=gh
        export CODACY_USERNAME=hacatu
        export CODACY_PROJECT_NAME=Crater
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l C -r build/debug/notes/combined.info
    - name: Deploy Coverage and Docs to Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: website
